name: Deploy

on:
  push:
    branches:
      - master

env:
  STAGING_BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Set production flag on staging

      - run: yarn
      - run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Deploy to S3: Staging'
        if: github.ref == 'refs/heads/dev'
        run: aws s3 sync build s3://${{ env.STAGING_BUCKET_NAME }}/app --delete